[supervisord]
nodaemon=true
user=root

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:xvfb]
command=Xvfb :0 -screen 0 %(ENV_RESOLUTION)s
autorestart=true

[program:nginx]
command=nginx -g "daemon off;" -c /etc/nginx/nginx.conf
autorestart=true

[program:fluxbox]
command=fluxbox
autostart=false
autorestart=true

[program:x11vnc]
command=x11vnc -display :0 -forever -shared -nopw -rfbport 5900 -noxdamage -bg -many
autostart=false
autorestart=true

[program:novnc]
command=websockify --web /usr/share/novnc/ 8081 localhost:5900
autostart=false
autorestart=true

[program:dashboard]
command=python3 /dashboard.py
autorestart=true

[program:chromium]
command=chromium --no-sandbox --disable-dev-shm-usage --start-maximized --no-first-run --disable-infobars --load-extension=/extension --disable-gpu --disable-software-rasterizer --js-flags="--max-old-space-size=512" --disable-background-networking --disable-sync --disable-default-apps --mute-audio --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-renderer-backgrounding "https://aistudio.google.com/apps/74c5f9d8-07fa-4fee-b8af-a22a8069811d?showPreview=true&showAssistant=true"
autorestart=true
environment=DISPLAY=":0"
