[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=Xvfb :0 -screen 0 %(ENV_RESOLUTION)s
autorestart=true

[program:fluxbox]
command=fluxbox
autorestart=true

[program:x11vnc]
command=x11vnc -display :0 -forever -shared -nopw -rfbport 5900 -noxdamage -bg -many
autostart=false
autorestart=true

[program:novnc]
command=websockify --web /usr/share/novnc/ 6080 localhost:5900
autostart=false
autorestart=true

[program:dashboard]
command=python3 /dashboard.py
autorestart=true
environment=PORT="5000"

[program:nginx]
command=nginx -c /nginx.conf -g "daemon off;"
autorestart=true

[program:chromium]
command=chromium --no-sandbox --disable-dev-shm-usage --start-maximized --no-first-run --disable-infobars --load-extension=/extension --disable-gpu --disable-software-rasterizer --js-flags="--max-old-space-size=512" --disable-background-networking --disable-sync --disable-default-apps --mute-audio --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-renderer-backgrounding
autorestart=true
environment=DISPLAY=":0"
