[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=Xvfb :0 -screen 0 %(ENV_RESOLUTION)s
autorestart=true

[program:fluxbox]
command=fluxbox
autorestart=true

[program:x11vnc]
command=x11vnc -display :0 -forever -shared -nopw -rfbport 5900 -noxdamage -bg -many
autorestart=true

[program:novnc]
command=websockify --web /usr/share/novnc/ %(ENV_PORT)s localhost:5900
autorestart=true

[program:chromium]
command=chromium --no-sandbox --disable-dev-shm-usage --start-maximized --no-first-run --disable-infobars --load-extension=/extension --disable-gpu --disable-software-rasterizer --js-flags="--max-old-space-size=512" --disable-background-networking --disable-sync --disable-default-apps --mute-audio --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-renderer-backgrounding "https://aistudio.google.com/apps/74c5f9d8-07fa-4fee-b8af-a22a8069811d?showPreview=true&showAssistant=true"
autorestart=true
environment=DISPLAY=":0"
